get-corresponding-derive/src/lib.rs, src/lib.rs, src/relations.rs
20s to 16s without significant RAM overhead.
=> Add shortcuts around vehicle_journeys

src/lib.rs, src/ntfs.rs, src/objects.rs
Navitia doesn't use the stop point contributor link, thus be consistent with navitia.
=> Add datasets

src/ntfs.rs, src/objects.rs
=> Added calendar dates

Cargo.toml, src/gtfs.rs, src/lib.rs, src/ntfs.rs, src/objects.rs, src/utils.rs
- Added Company (related to https://github.com/CanalTP/navitia/pull/2282)
- Updated PhysicalMode
- Updated Route
- Added NaiveDate for dates fix https://github.com/CanalTP/navitia_model/issues/17
=> Added company and completed some models

examples/gtfs_reader.rs, examples/test.rs, src/collection.rs, src/gtfs.rs, src/lib.rs, src/ntfs.rs, src/objects.rs, src/relations.rs, src/utils.rs, tests/gtfs_reader.rs
The LICENSE file was added in another commit thanks to the github "add license" feature
=> Add license headers

Cargo.toml, src/collection.rs, src/ntfs/mod.rs, src/ntfs/read.rs, src/ntfs/write.rs, src/objects.rs
=> [NTM to NTFS] writing feed_infos.txt and networks.txt

Cargo.toml, src/bin/gtfs2ntfs.rs
=> Added basic command to convert gtfs to ntfs

.gitignore, src/gtfs/mod.rs, src/gtfs/read.rs, src/objects.rs
Work is partial, but I don't want to wait and have a too big PR.
Yet to be done : 
* creating lines from gtfs routes when gtfs contains routes
* moving/creating methods around physical_modes in the model to mutualize their use in connectors
=> Gtfs - read routes.txt and load mdoes and lines

.dockerignore, Dockerfile
```
docker build -t gtfs2ntfs .
docker run --rm -v /path/to/gtfs_files:/app/input -v path/to/output:/app/output gtfs2ntfs
```
=> added dockerfile

Cargo.toml, examples/test.rs, src/collection.rs, src/gtfs/mod.rs, src/gtfs/read.rs, src/lib.rs, src/ntfs/mod.rs, src/ntfs/read.rs, src/relations.rs, tests/read_ntfs.rs
```
$ ../../target/debug/examples/test
Error indexing lines_to_routes
id="M" not found
$ ../../target/debug/examples/test
Error reading "./stop_times.txt"
CSV deserialize error: record 4 (line: 5, byte: 146): format should be HH:MM:SS
$ ../../target/debug/examples/test
Error reading "./stop_times.txt"
CSV deserialize error: record 1 (line: 2, byte: 57): missing field `trip_id`
$ ../../target/debug/examples/test
Error reading "./feed_infos.txt"
No such file or directory (os error 2)
$ ../../target/debug/examples/test
Error reading "./lines.txt"
CSV deserialize error: record 3 (line: 4, byte: 101): RgbError_NumberOfChar
```
=> Error management

Cargo.toml, examples/gtfs_reader.rs, src/bin/gtfs2ntfs.rs, src/gtfs/mod.rs, src/gtfs/read.rs
json file expected should look like:
```json
{
"contributor": {
"contributor_id": "OIF",
"contributor_name": "OIF - STIF Ile de France",
"contributor_website": "http://www.vianavigo.com",
"contributor_license": "ODbL"
},
"dataset": {
"contributor_id": "OIF",
"dataset_id": "OIF:0",
"dataset_start_date": "20170607",
"dataset_end_date": "20170702",
"dataset_type": "0",
"dataset_desc": "NIO_auto_20170618",
"dataset_system": "GTFS V2 Ligne",
"dataset_extrapolation": 0
}
}
```
to test:
```
cargo run -- -i /path/to/input -o /path/to/output -c /path/to/config
```
=> read gtfs config from json file

examples/gtfs_reader.rs, src/bin/gtfs2ntfs.rs, src/collection.rs, src/gtfs/mod.rs, src/gtfs/read.rs, src/objects.rs
- refactoring add prefix
- create contributor+ dataset related to https://github.com/CanalTP/navitia_model/pull/57/files#diff-a3fce5151b3ec922f7e1e2ed742d4ea2R28
fix https://github.com/CanalTP/navitia_model/issues/61
=> refactoring prefix

examples/test.rs, get-corresponding-derive/src/lib.rs, src/collection.rs, src/common_format.rs, src/gtfs/mod.rs, src/gtfs/read.rs, src/lib.rs, src/model.rs, src/ntfs/mod.rs, src/ntfs/read.rs, src/ntfs/write.rs, src/objects.rs, src/relations.rs, tests/read_ntfs.rs
=> Applied rustfmt again and again

get-corresponding-derive/src/lib.rs, src/relations.rs
https://jira.canaltp.fr/browse/NAVP-774
https://jira.canaltp.fr/browse/NAVP-776
=> Document the relations module and the usage of GetCorresponding

fixtures/ntfs/comment_links.txt, fixtures/ntfs/comments.txt, src/objects.rs, src/utils.rs, tests/read_ntfs.rs
=> comments: valid reading from spec + robustness for bad files

src/collection.rs, src/gtfs/mod.rs, src/gtfs/read.rs, src/objects.rs, src/utils.rs
Read comments, comment_links and equipments for gts into NTM
=> Finish read stops gtfs

src/collection.rs, src/gtfs/mod.rs, src/gtfs/read.rs, src/objects.rs
from GTFS trips generate 
- Vehicle journeys
- Trip properties
related to https://github.com/CanalTP/navitia_model/pull/57
=> Gtfs trips to NTM vehicle journeys and trip properties

src/gtfs/mod.rs, src/objects.rs
Added some prefixes in:
- trip_property_id in VehicleJourney object
- commercial_mode_id in Line and CommercialMode
=> Forgot some prefixes

src/collection.rs, src/common_format.rs, src/gtfs/mod.rs, src/gtfs/read.rs, src/ntfs/mod.rs, src/ntfs/read.rs, src/objects.rs, src/relations.rs
fix https://jira.canaltp.fr/browse/ND-43
=> fix duplicate equipments

src/collection.rs, src/objects.rs
Adding `push` fn  to `Collection` and `FromStr` trait on `Time` struct.
=> Add some extentions to model

.travis.yml, src/gtfs/read.rs, src/model.rs, src/objects.rs, src/relations.rs, src/utils.rs
Dear fmt,
Can you please stabilize very quickly?
a frustrated developer
=> Updated fmt

Cargo.toml, src/gtfs/mod.rs, src/gtfs/read.rs, src/lib.rs, src/ntfs/mod.rs, src/ntfs/read.rs, src/objects.rs, src/utils.rs
needs https://github.com/CanalTP/rust-wkt/pull/2 to be merged in https://github.com/georust/rust-wkt
- Read GTFS shapes => convert them into geo_types::Geometry
- Deserialize WKT geometries from NTFS 
- Serialize geo_types::Geometry into WKT string
=> read gtfs shapes

examples/gtfs_reader.rs, examples/test.rs, src/bin/netex2ntfs.rs, src/bin/ntfs2ntfs.rs
https://docs.rs/failure/0.1.2/failure/struct.Error.html#method.causes
=> Fix depreciation: Error:causes

Dockerfile, README.md, src/bin/transfers.rs, src/lib.rs, src/model.rs, src/transfers.rs
=> Basic generation of transfers

Dockerfile, README.md, fixtures/merge-ntfs/calendar.txt, fixtures/merge-ntfs/comments.txt, fixtures/merge-ntfs/commercial_modes.txt, fixtures/merge-ntfs/companies.txt, fixtures/merge-ntfs/contributors.txt, fixtures/merge-ntfs/datasets.txt, fixtures/merge-ntfs/feed_infos.txt, fixtures/merge-ntfs/lines.txt, fixtures/merge-ntfs/networks.txt, fixtures/merge-ntfs/physical_modes.txt, fixtures/merge-ntfs/routes.txt, fixtures/merge-ntfs/stop_times.txt, fixtures/merge-ntfs/stops.txt, fixtures/merge-ntfs/trips.txt, src/bin/merge-ntfs.rs, src/collection.rs, src/model.rs, tests/merge_ntfs.rs
to test, run: 
```
cargo run --bin merge fixtures/minimal_ntfs fixtures/merge -o output
```
=> add merge binary for ntfs

src/gtfs/read.rs, src/objects.rs, src/read_utils.rs
=> Added prefixes on Geometries and calendars

src/gtfs/read.rs, src/objects.rs
=> fix previous pr on prefixes

src/gtfs/read.rs
Sometimes a GTFS contains shapes without coordinates  so we have the foloowinf error `"gtfs2ntfs: Error reading \"/tmp/tmpq_rtu4_v/shapes.txt\"\nCSV deserialize error: record 43 (line: 43, byte: 1304): field 1: cannot parse float from empty string"`
This PR fix that ignoring shapes with empty points but  breaksthe GTFS model
I might match the corresponding error when deserializing a shape.
If you have an idea.
=> Fix shape without coordinates

src/bin/transfers.rs, src/collection.rs, src/objects.rs, src/transfers.rs
Add and/or remove transfer from a csv files that contain
from_stop_id|to_stop_id|transfer_time| |
--|--|--|--
SP1|SP2| | no time specified, will be removed
SP3|SP2|111 | added
UNKNOWN|SP2|454 | ignored as UNKNOWN is an unknown stop   
UNKNOWN|SP2|| ignored as UNKNOWN is an unknown stop
=> Manage transfer exceptions

src/gtfs/read.rs
fix `gtfs2ntfs: Error indexing networks_to_lines\nid=\"KSM:default_agency_id\" not found`
and same error with `companies_to_vehicle_journeys`
=> Fix relations networks<->lines and companies<->vj with routes without agency id

src/documentation/ntfs2gtfs.md, src/gtfs/mod.rs, src/gtfs/read.rs, src/gtfs/write.rs
see https://github.com/CanalTP/navitia_model/blob/master/src/documentation/ntfs2gtfs.md#stopstxt
=> [ntfs2gtfs] write stops.txt

src/gtfs/mod.rs, src/gtfs/read.rs, src/gtfs/write.rs
see https://github.com/CanalTP/navitia_model/blob/master/src/documentation/ntfs2gtfs.md#transferstxt
fix https://github.com/CanalTP/tartare/issues/746
=> [ntfs2gtfs] write transfers.txt

src/common_format.rs, src/gtfs/mod.rs, src/gtfs/write.rs, src/ntfs/mod.rs, src/ntfs/write.rs
see https://github.com/CanalTP/navitia_model/blob/master/src/documentation/ntfs2gtfs.md#calendar_datestxt
=> [ntfs2gtfs] write calendar_dates.txt

src/gtfs/mod.rs, src/gtfs/write.rs
see https://github.com/CanalTP/navitia_model/blob/master/src/documentation/ntfs2gtfs.md#stop_extensionstxt
fix https://github.com/CanalTP/tartare/issues/748
=> [ntfs2gtfs] write stop_extensions.txt

src/gtfs/mod.rs, src/gtfs/read.rs, src/gtfs/write.rs
see https://github.com/CanalTP/navitia_model/blob/master/src/documentation/ntfs2gtfs.md#shapestxt
=> [ntfs2gtfs] write shapes.txt

src/gtfs/write.rs
fix https://github.com/CanalTP/tartare/issues/782
=> use route.line_id instead trip.route_id

src/documentation/ntfs2gtfs.md, src/gtfs/mod.rs, src/gtfs/read.rs, src/gtfs/write.rs
see https://github.com/CanalTP/navitia_model/blob/master/src/documentation/ntfs2gtfs.md#routestxt
=> [ntfs2gtfs] Write routes.txt

src/gtfs/mod.rs
this PR is just for you @pbougue :)
=> Added link to documentation NTFS to GTFS conversion

src/gtfs/mod.rs, src/gtfs/read.rs, src/utils.rs
pl_warsaw data set contains spaces before certain longitudes
=> trim location coordinates from gtfs stop points

src/gtfs/read.rs, src/gtfs/write.rs, src/model.rs
fix https://github.com/CanalTP/navitia_model/issues/130
=> Write ntfs stop code

fixtures/merge-ntfs/stop_times.txt, src/collection.rs, src/documentation/ntfs2gtfs.md, src/gtfs/mod.rs, src/gtfs/read.rs, src/gtfs/write.rs, src/model.rs, src/ntfs/mod.rs, src/ntfs/read.rs, src/ntfs/write.rs, tests/merge_ntfs.rs
bench on ntfs2ntfs fr-idf
| | without headsign | with headsign
| --- | --- | ---
| Mem | 1,550GB | 1,563GB
| Time | 35s | 33s
=> manage stop time headsign

src/model.rs, src/ntfs/mod.rs, src/ntfs/write.rs
this will allow to compare outputs with fixtures
=> Order feed infos by info_params ASC

src/gtfs/mod.rs, src/gtfs/read.rs, src/objects.rs
fix https://github.com/CanalTP/tartare/issues/807
=> handle invalid color as None

src/gtfs/read.rs
with https://github.com/AFDLab4Dev/AccraMobility/raw/master/GTFS/GTFS_Accra.zip
```
target/debug/gtfs2ntfs -i path/to/accra/dataset -o output
```
=> extend trip_id autoincrement counter to avoid overflow

model-builder/src/builder.rs, src/objects.rs
add a way to add some calendars to the builder.
btw there is a confusion between `calendar` and `service`, I know this confusion comes from the GTFS, but shouldn't we always use the same term ?
=> add a way to specify the calendar of the trip

fixtures/kv12ntfs/input/NOTICEXXXX.TMI, fixtures/kv12ntfs/input/NTCASSGNMX.TMI, fixtures/kv12ntfs/output/comment_links.txt, fixtures/kv12ntfs/output/comments.txt, src/kv1/mod.rs, src/kv1/read.rs, tests/read_kv1.rs
Convert KV1 comments files (NOTICEXXXX.TMI/NTCASSGNMX.TMI) to NTFS (comments.txt/comment_links.txt)
=> KV1 - Add Notices/Comments files

src/documentation/nl_syntus_fares_read.md
Based on the new NTFS fare model: https://github.com/CanalTP/navitia/pull/2791
=> Doc fares: update connector HelloGo

CHANGELOG.md, fixtures/apply_rules/input/feed_infos.txt, fixtures/enrich-with-hellogo-fares/input/ntfs_with_prefix/feed_infos.txt, fixtures/enrich-with-hellogo-fares/input/ntfs_without_prefix/feed_infos.txt, fixtures/filter_ntfs/input/feed_infos.txt, fixtures/filter_ntfs/output_extract/feed_infos.txt, fixtures/filter_ntfs/output_remove/feed_infos.txt, fixtures/gtfs2ntfs/minimal/output/feed_infos.txt, fixtures/gtfs2ntfs/minimal_with_config/output/feed_infos.txt, fixtures/kv12ntfs/output/feed_infos.txt, fixtures/merge-ntfs/output/feed_infos.txt, fixtures/merge-ntfs/output_feedinfos/feed_infos.txt, fixtures/merge-stop-areas/output/feed_infos.txt, fixtures/minimal_ntfs/feed_infos.txt, fixtures/ntfs/feed_infos.txt, fixtures/ntfs2gtfs/input/feed_infos.txt, fixtures/ntfs2ntfs/fares/feed_infos.txt, fixtures/restrict-validity-period/input/feed_infos.txt, fixtures/restrict-validity-period/output/feed_infos.txt, src/lib.rs, src/ntfs/mod.rs
=> Ntfs version 0.9

fixtures/ntfs2ntfs/empty_od_fares/calendar.txt, fixtures/ntfs2ntfs/empty_od_fares/commercial_modes.txt, fixtures/ntfs2ntfs/empty_od_fares/companies.txt, fixtures/ntfs2ntfs/empty_od_fares/contributors.txt, fixtures/ntfs2ntfs/empty_od_fares/datasets.txt, fixtures/ntfs2ntfs/empty_od_fares/fares.csv, fixtures/ntfs2ntfs/empty_od_fares/feed_infos.txt, fixtures/ntfs2ntfs/empty_od_fares/lines.txt, fixtures/ntfs2ntfs/empty_od_fares/networks.txt, fixtures/ntfs2ntfs/empty_od_fares/od_fares.csv, fixtures/ntfs2ntfs/empty_od_fares/physical_modes.txt, fixtures/ntfs2ntfs/empty_od_fares/prices.csv, fixtures/ntfs2ntfs/empty_od_fares/routes.txt, fixtures/ntfs2ntfs/empty_od_fares/stop_times.txt, fixtures/ntfs2ntfs/empty_od_fares/stops.txt, fixtures/ntfs2ntfs/empty_od_fares/trips.txt, fixtures/ntfs2ntfs/fares/object_codes.txt, model-builder/Cargo.toml, src/ntfs/mod.rs, tests/read_ntfs.rs
Write Fare V1 if od_fares is  empty and prices not empty
=> Write Fare V1 if od_fares empty

Cargo.toml, src/apply_rules.rs, src/common_format.rs, src/gtfs/mod.rs, src/gtfs/read.rs, src/gtfs/write.rs, src/kv1/read.rs, src/merge_stop_areas.rs, src/model.rs, src/ntfs/mod.rs, src/ntfs/read.rs, src/objects.rs, src/read_utils.rs, src/transfers.rs, src/utils.rs
Considering this is the [documented](https://serde.rs/derive.html) way of using the 'derive' with Serde...
=> Configure 'serde' with 'derive' feature as documented

.travis.yml, Cargo.toml, src/bin/transxchange2ntfs.rs, src/lib.rs, src/transxchange/mod.rs, src/transxchange/read.rs
Note: I ordered all dependencies in the `Cargo.toml` in alphabetical order.
=> Add 'transxchange2ntfs' binary under a featured compilation

src/documentation/transxchange_read.md
This initial version contains the specs for :
- stops (from Naptan + TXC)
- networks
- lines (+modes)
- services/calendars (this might need to be revised in a later version).
=> Doc: First version of TransXChange connector

Cargo.toml, src/gtfs/write.rs, src/ntfs/mod.rs, src/test_utils.rs
https://github.com/rust-lang-deprecated/tempdir
=> Use tempfile crate instead of deprecated tempdir crate

src/collection.rs, src/gtfs/write.rs, src/model.rs, src/ntfs/mod.rs, src/ntfs/write.rs, src/transxchange/read.rs
Often, we want to create a `Collection` or a `CollectionWithId` out of only one element. Implementation of `From<T> for Collection<T>` and `From<T> for CollectionWithId<T>` should help with that.
=> Implementation of From<T> for Collection<T> and CollectionWithId<T>

src/minidom_utils/try_only_child.rs
In transXChange, we're often gonna select one of the children based on it's `id` attribute. Giving this filtering ability is gonna simplify some node selection.
=> Enhance TryOnlyChild with filters

Cargo.toml, fixtures/transxchange2ntfs/input/naptan/Stops.csv, fixtures/transxchange2ntfs/input/transxchange/no-mode.xml, fixtures/transxchange2ntfs/input/transxchange/simple.xml, fixtures/transxchange2ntfs/output/ntfs/stop_times.txt, fixtures/transxchange2ntfs/output/ntfs/stops.txt, fixtures/transxchange2ntfs/output/ntfs/trips.txt, src/objects.rs, src/transxchange/read.rs, tests/read_transxchange.rs
Integration tests are missing and are making the build breaks.
=> Load routes, trips and stop times for TransXChange

src/documentation/transxchange_read.md
Picking the specs TXC up where I left off, starting with routes.
=> Specs TXC: adding routes

src/test_utils.rs
Instead of comparing files content as a big `String`, I'm loading each CSV file line by line into a `HashSet` and compare the 2 resulting `HashSet`.
Note that I couldn't remove the function `get_file_content` because it's also used in the integration tests of `apply-rules` for comparing the reports.
=> Do not depend on order of lines for CSV comparison

src/bin/transxchange2ntfs.rs
It was somewhere in my lost branches so here it is as a PR.
=> Add documentation about what is accepted as input

src/gtfs/read.rs, src/ntfs/read.rs, src/objects.rs, src/transxchange/naptan.rs
Not sure about the solution is optimal but here is a first draft. I'm open to suggestion.
=> Factorize the StopArea creation for orphan StopPoint

fixtures/transxchange2ntfs/input/transxchange/no-mode.xml, fixtures/transxchange2ntfs/input/transxchange/simple.xml, fixtures/transxchange2ntfs/output/ntfs/companies.txt, fixtures/transxchange2ntfs/output/ntfs/lines.txt, fixtures/transxchange2ntfs/output/ntfs/networks.txt, fixtures/transxchange2ntfs/output/ntfs/trips.txt, src/collection.rs, src/transxchange/read.rs
This is an alternative to #344 where the `MergeWith` trait is using a closure that takes the two elements in conflict.
=> Upgrade network/company name if possible

fixtures/transxchange2ntfs/input/transxchange/simple.xml, fixtures/transxchange2ntfs/output/ntfs/trips.txt, src/transxchange/read.rs
This is not a full implementation of the specification but it should be enough for Wales dataset so far.
=> Add 'head_sign' for trips in TransXChange

Cargo.toml, src/transxchange/bank_holidays.rs, src/transxchange/mod.rs, src/transxchange/operating_profile.rs, src/transxchange/read.rs, tests/fixtures/transxchange2ntfs/input/bank-holiday.json, tests/fixtures/transxchange2ntfs/input/transxchange/02_simple.xml, tests/fixtures/transxchange2ntfs/output/ntfs/calendar_dates.txt, tests/read_transxchange.rs
I'm opening this PR as a draft PR because even if the code might be working fine (at least, the few tests I have seems to work), I'm not satisfied about the structure of the code. I'm open to ideas.
Note: I'm currently working on adding integration tests too.
=> Add bank holidays management in TransXChange

src/netex_idf/mod.rs, src/netex_idf/read.rs, src/netex_idf/stops.rs
- with bad coord (will be calculated with barycenter of stop points)
=> [feature] Netex IDF: load stop areas

src/netex_idf/stops.rs
a refactoring will be done in the following PR
=> [feature] Netex IDF: read stop points

src/netex_idf/lines.rs
Allow multiple networks or companies within one frame.
Nb : It was not clear in the specifications.
=> Netex idf networks companies (update)

src/netex_idf/stops.rs
just a refactoring
needs https://github.com/CanalTP/transit_model/pull/373
=> Netex stops: split code in some functions

tests/fixtures/netexidf2ntfs/output/equipments.txt, tests/netexidf2ntfs.rs
=> [Netex IDF] add fixtures for equipments

.mergify.yml
I doesn't work the way we want so let's remove that constraint.
=> Remove 'commented reviews' constraint

src/netex_idf/lines.rs, src/netex_idf/read.rs, tests/fixtures/netexidf2ntfs/input/netex/lignes.xml, tests/fixtures/netexidf2ntfs/output/companies.txt, tests/fixtures/netexidf2ntfs/output/lines.txt, tests/fixtures/netexidf2ntfs/output/networks.txt, tests/fixtures/netexidf2ntfs/output/object_codes.txt, tests/netexidf2ntfs.rs
Additional data management will be done in another PR (like color, private code, comments, accessibility,...)
=> Netex IDF: Load networks, companies, lines and modes

src/documentation/netex_idfm_to_ntfs.md
Updating readings for lines, network, operator according to PTA validation
=> Netex spec v2 lines - Updating readings for lines, network, operator

src/netex_idf/stops.rs, tests/fixtures/netexidf2ntfs/input/netex/arrets.xml, tests/fixtures/netexidf2ntfs/output/stops.txt
without equipments
+ compute stop area coordinates with centroid of stop points stop area has no coordinates
=> Netex IDF: Load stop points

Cargo.toml, relations/Cargo.toml
Add `version` and `path` as described in [documentation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies).
=> Improve version definition

src/documentation/netex_idfm_to_ntfs.md
=> netex_idfm_to_ntfs spec - improve schedule part of the spec

src/netex_idf/offers.rs, tests/fixtures/netexidf2ntfs/input/netex/OFFRE_TP/offre_tp.xml
This is needed for the parsing of the trips.
=> Add object_code to route in Netex IDFM

src/netex_idf/calendars.rs, src/netex_idf/offers.rs, tests/fixtures/netexidf2ntfs/input/netex/OFFRE_TP/offre_tp.xml
A first partial PR for parsing vehicle journeys. More to come.
=> Parse vehicle journeys in Netex IDFM

src/model.rs, tests/fixtures/restrict-validity-period/input/comment_links.txt, tests/fixtures/restrict-validity-period/input/comments.txt, tests/fixtures/restrict-validity-period/output/comment_links.txt, tests/fixtures/restrict-validity-period/output/comments.txt, tests/restrict_validity_period.rs
comments only on stop times were removed.
=> Fix sanitize comments on stop times

src/documentation/netex_idfm_to_ntfs.md, src/netex_idf/offers.rs, tests/fixtures/netexidf2ntfs/input/netex/OFFRE_TP/offre_tp.xml, tests/fixtures/netexidf2ntfs/output/object_codes.txt, tests/fixtures/netexidf2ntfs/output/physical_modes.txt, tests/fixtures/netexidf2ntfs/output/stop_times.txt, tests/fixtures/netexidf2ntfs/output/trips.txt, tests/netexidf2ntfs.rs
=> Netex IDF: stop times

src/documentation/ntfs_fare_v2_to_v1_specs.md
Following a discussion with @ArnaudOggy and @papailio, I'm proposing these modifications to indicate there could be unexpected behavior in navitia in some cases.
=> Doc: Fare V2->V1 precisions and examples

relations/Cargo.toml, relations/src/relations.rs, src/gtfs/read.rs, src/kv1/read.rs, src/model.rs, src/test_utils.rs, src/transxchange/naptan.rs
=> [tech] removed clippy warnings

src/documentation/ntfs_to_netex_france_specs.md
Here is an example of the output format.
```xml
<?xml version="1.0" encoding="UTF-8"?>                                                                       
<PublicationDelivery                                                                                         
version="1.09:FR-NETEX_LIGNE-2.1-1.0"                                                                      
xmlns="http://www.netex.org.uk/netex"                                                                      
xmlns:core="http://www.govtalk.gov.uk/core"                                                                
xmlns:gml="http://www.opengis.net/gml/3.2"                                                                 
xmlns:ifopt="http://www.ifopt.org.uk/ifopt" …
```
=> [doc] Specification for trips and stop_times on NeTEx France

README.md, src/documentation/ntfs_to_netex_france_specs.md, src/lib.rs, src/netex_france/modes.rs, src/ntfs/mod.rs, src/ntfs/write.rs, tests/fixtures/filter_ntfs/output_extract/feed_infos.txt, tests/fixtures/filter_ntfs/output_extract_multiple_lines/feed_infos.txt, tests/fixtures/filter_ntfs/output_remove/feed_infos.txt, tests/fixtures/filter_ntfs/output_remove_line/feed_infos.txt, tests/fixtures/gtfs2ntfs/minimal/output/feed_infos.txt, tests/fixtures/gtfs2ntfs/minimal_with_config/output/feed_infos.txt, tests/fixtures/kv12ntfs/output/feed_infos.txt, tests/fixtures/merge-ntfs/output/feed_infos.txt, tests/fixtures/merge-ntfs/output_feedinfos/feed_infos.txt, tests/fixtures/merge-stop-areas/output/feed_infos.txt, tests/fixtures/netexidf2ntfs/output/feed_infos.txt, tests/fixtures/restrict-validity-period/output/feed_infos.txt, tests/fixtures/transxchange2ntfs/output/ntfs/feed_infos.txt
Need https://github.com/CanalTP/ntfs-specification/pull/17 to be merged and v0.11.2 to be released first.
=> [feature] Add 'feed_creation_datetime' in 'feed_infos.txt'

Cargo.toml, transit_model_procmacro/Cargo.toml
I also reverted the previous commit that was not needed.
=> [tech] Remove quote:1.0.3 from the build (broken version)

src/documentation/ntfs_to_netex_france_specs.md, src/netex_france/stops.rs, tests/fixtures/netex_france/input_gtfs/stops.txt, tests/fixtures/netex_france/input_ntfs/stops.txt, tests/fixtures/netex_france/output/arrets.xml
Fix https://github.com/CanalTP/tartare-tools/issues/59
=> [tech] NeTEx France - Fix AccessibilityAssessment uniqueness

.travis.yml
Until we can restart jobs in GitHub Actions
=> [ci] Minimal travis come-back

README.md
new badges with links inspired by [`anyhow`](https://github.com/dtolnay/anyhow)
see https://github.com/CanalTP/transit_model/pull/627/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8
=> beautiful badges

src/gtfs/read.rs, src/gtfs/write.rs, src/model.rs, src/ntfs/filter.rs, src/ntfs/mod.rs, src/ntfs/read.rs, src/ntfs/write.rs, tests/read_ntfs.rs
Reverts CanalTP/transit_model#625
=> [tech] use of ids instead of indexes for stop_times optional fields

src/documentation/gtfs_to_ntfs_specs.md
- Adding the two parameters odt and odt_comment
- Changing date_time_estimated to stop_time_precision
=> [doc] Handling ODT when reading gtfs

Cargo.toml, gtfs2netexfr/README.md, gtfs2ntfs/README.md, ntfs2gtfs/README.md, ntfs2netexfr/README.md, ntfs2ntfs/README.md
and fixed some warnings/errors form my markdown linter (https://github.com/DavidAnson/markdownlint/blob/v0.20.3/doc/Rules.md#rules)
fix https://github.com/CanalTP/transit_model/issues/646
=> [doc] fix the installation of binairies

Cargo.toml, ntfs2ntfs/README.md, restrict-validity-period/Cargo.toml, restrict-validity-period/README.md, restrict-validity-period/src/main.rs, src/gtfs/read.rs, src/validity_period.rs
Add the binary to transit_model.
Move some related tests closer to the code they test.
:mag: review by commit is advised
=> [feature] Add binary restrict-validity-period in its crate

CONTRIBUTING.md, Cargo.toml, README.md, gtfs2netexfr/README.md, gtfs2ntfs/README.md, ntfs2gtfs/README.md, ntfs2netexfr/README.md, restrict-validity-period/README.md, src/documentation/gtfs_to_ntfs_specs.md, src/documentation/ntfs_to_gtfs_specs.md, src/gtfs/mod.rs, src/lib.rs
Only rewrite main readme for now (only links should change after this PR).
Everything else I have in mind for doc should be in other files IMO (contributing, other readme).
Also dispatched some content in more appropriate files (may be refactored there later).
=> [doc] Improve after code moves, part 1

src/model.rs
=> [tech] Improve performances for route_name generation

Cargo.toml, gtfs2netexfr/Cargo.toml, gtfs2ntfs/Cargo.toml, ntfs2gtfs/Cargo.toml, ntfs2netexfr/Cargo.toml, ntfs2ntfs/Cargo.toml, restrict-validity-period/Cargo.toml
PR https://github.com/CanalTP/transit_model/pull/663 was a breaking change so we should bump a major version for the next release.
=> [feature] Bump for breaking change

src/gtfs/mod.rs, src/gtfs/write.rs
=> [tech] fix multimodal line splitting

src/add_prefix.rs
Hint: Look at the diff with "Ignored Whitespace", it should ease the review.
=> [feature] Do not subprefix when no data_prefix is present

Cargo.toml, gtfs2netexfr/Cargo.toml, gtfs2ntfs/Cargo.toml, ntfs2gtfs/Cargo.toml, ntfs2netexfr/Cargo.toml, ntfs2ntfs/Cargo.toml, restrict-validity-period/Cargo.toml, src/gtfs/read.rs, src/gtfs/write.rs, src/model.rs, src/ntfs/mod.rs, src/objects.rs, src/utils.rs
=> [tech] upgrade crates

CONTRIBUTING.md
Small PR to update to the latest version of NeTex FR norm. Also added a small tweak to the documentation.
=> [tech] Support last version of NeTeX norm

Cargo.toml, src/ntfs/mod.rs, src/objects.rs, src/utils.rs
=> [feature] default value for transfer time

Cargo.toml, gtfs2netexfr/Cargo.toml, gtfs2ntfs/Cargo.toml, ntfs2gtfs/Cargo.toml, ntfs2netexfr/Cargo.toml, ntfs2ntfs/Cargo.toml, restrict-validity-period/Cargo.toml, src/gtfs/read.rs, src/lib.rs, src/ntfs/mod.rs, src/ntfs/write.rs, src/objects.rs, tests/fixtures/gtfs2ntfs/full_output/feed_infos.txt, tests/fixtures/gtfs2ntfs/minimal/output/feed_infos.txt, tests/fixtures/restrict-validity-period/output/feed_infos.txt
=> [feature] add object codes on companies

Cargo.toml, src/ntfs/read.rs, src/ntfs/write.rs
=> [fix] read object codes on companies

src/gtfs/write.rs
=> [feature] remove transfers at the same stop point in gtfs export

ntfs2gtfs/tests/fixtures/output/stop_times.txt, ntfs2gtfs/tests/fixtures/output/trips.txt, src/gtfs/mod.rs
=> [fix] removal of trips containing stop zone

src/gtfs/read.rs
Here is an idea to address this [comment](https://github.com/CanalTP/transit_model/pull/741#issuecomment-773359625).
=> [tech] Refactorization of generate comment for GTFS read_as_line 

src/objects.rs
=> [fix] allow millisecond in schedule

.dockerignore, Dockerfile
:heavy_check_mark: Tested OK locally
=> [fix] allow git-version in dockerfile

src/ntfs/read.rs
=> [feature] log error vj with inconsistent schedules

documentation/ntfs_to_gtfs_specs.md, ntfs2gtfs/tests/fixtures/output/trips.txt, src/gtfs/write.rs
=> [feature] Improved management trip shortname headsign

Cargo.toml, model-builder/Cargo.toml, src/gtfs/read.rs
Depends on CanalTP/relational_types#12.
=> [feature] bump to typed_index_collection:v2.0.0

src/gtfs/mod.rs, src/netex_utils/mod.rs, src/objects.rs
:warning: Wait for rust ci image update before merging
=> [tech] update clippy cargo 1.53

src/model.rs, src/objects.rs, src/test_utils.rs, tests/fixtures/netex_france/output/correspondances.xml, tests/fixtures/ntfs_complete_with_duplicated_ids/admin_stations.txt, tests/fixtures/ntfs_complete_with_duplicated_ids/frequencies.txt, tests/fixtures/ntfs_complete_with_duplicated_ids/grid_calendars.txt, tests/fixtures/ntfs_complete_with_duplicated_ids/grid_exception_dates.txt, tests/fixtures/ntfs_complete_with_duplicated_ids/grid_periods.txt, tests/fixtures/ntfs_complete_with_duplicated_ids/grid_rel_calendar_line.txt, tests/fixtures/ntfs_complete_with_duplicated_ids/ticket_prices.txt, tests/fixtures/ntfs_complete_with_duplicated_ids/ticket_use_perimeters.txt, tests/fixtures/ntfs_complete_with_duplicated_ids/ticket_use_restrictions.txt, tests/fixtures/ntfs_complete_with_duplicated_ids/ticket_uses.txt, tests/fixtures/ntfs_complete_with_duplicated_ids/tickets.txt, tests/read_ntfs.rs
ref: ND-1375
Tested on TT :heavy_check_mark:
=> [feature] deduplicate collection

.github/workflows/dockerhub-publish.yml
=> [tech] add dockerhub publication github action

.github/workflows/dockerhub-publish.yml
=> [fix] remove useless secrets

.github/workflows/dockerhub-publish.yml
=> [tech] Add failure notif on DockerHub publish

Cargo.toml, ntfs2gtfs/tests/fixtures/input/stops.txt, ntfs2gtfs/tests/fixtures/output/stops.txt, src/gtfs/write.rs
=> [fix] Export stopcode for stoplocation

src/model.rs
=> [feature] pickup and drop off harmonisation

Cargo.toml, gtfs2netexfr/Cargo.toml, gtfs2ntfs/Cargo.toml, ntfs2gtfs/Cargo.toml, ntfs2netexfr/Cargo.toml, ntfs2ntfs/Cargo.toml
and revert versions of "sub-crates" that were bumped in the previous PR because it's useless...
=> [tech] bump 0.43.0

Cargo.toml, gtfs2netexfr/Cargo.toml, gtfs2netexfr/src/main.rs, gtfs2ntfs/Cargo.toml, gtfs2ntfs/src/main.rs, ntfs2gtfs/Cargo.toml, ntfs2gtfs/src/main.rs, ntfs2netexfr/Cargo.toml, ntfs2netexfr/src/main.rs, ntfs2ntfs/Cargo.toml, ntfs2ntfs/src/main.rs, restrict-validity-period/Cargo.toml, restrict-validity-period/src/main.rs
https://docs.rs/structopt/latest/structopt/#maintenance
=> [tech] Remove structopt, use clap directly

documentation/gtfs_to_ntfs_specs.md
=> docs: improve documentation about ODT parameters

Cargo.toml, src/gtfs/read.rs, tests/fixtures/gtfs2ntfs/full_output/object_codes.txt, tests/fixtures/gtfs2ntfs/minimal/output/object_codes.txt, tests/fixtures/gtfs2ntfs/routes_comments/output/object_codes.txt, tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/object_codes.txt
https://navitia.atlassian.net/browse/DATENG-451
=> Add missing object code

src/gtfs/read.rs, src/ntfs/read.rs
to avoid asking the question every 6 months :smile:
=> Add comment on GTFS/NTFS stoplocation reading

src/model.rs
Just because I happened to look at this piece of code today and thought about making this code a bit shorter (and simpler I think :thinking:).
=> style: use 'Option::zip' to write shorter code

Cargo.toml
For https://github.com/hove-io/transit_model/pull/891
=> [tech] Bump TransitModel v0.55.0

.github/workflows/auto-tagging.yml, Cargo.toml, model-builder/Cargo.toml
=> [tech] Fetch some crates from github

src/gtfs/read.rs, src/model.rs
Functional tests already covered by [gtfs2ntfs/tests/gtfs2ntfs.rs](https://github.com/hove-io/transit_model/blob/master/gtfs2ntfs/tests/gtfs2ntfs.rs)
=> [tech] Move gtfs frequencies to stoptimes conversion to collection impl

Cargo.toml, src/gtfs/read.rs, src/gtfs/write.rs, src/lib.rs, src/model.rs, src/ntfs/mod.rs, src/ntfs/read.rs, src/ntfs/write.rs, src/objects.rs, tests/fixtures/gtfs2ntfs/full_output/feed_infos.txt, tests/fixtures/gtfs2ntfs/minimal/output/feed_infos.txt, tests/fixtures/gtfs2ntfs/routes_comments/output/feed_infos.txt, tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/feed_infos.txt, tests/fixtures/minimal_ntfs/addresses.txt, tests/fixtures/minimal_ntfs/administrative_regions.txt, tests/fixtures/ntfs2ntfs/stops/addresses.txt, tests/fixtures/ntfs2ntfs/stops/administrative_regions.txt, tests/fixtures/restrict-validity-period/output/feed_infos.txt, tests/read_ntfs.rs
ref: https://navitia.atlassian.net/browse/NAV-2217
follows https://github.com/hove-io/ntfs-specification/pull/45
=> [feature] Add administrative regions

.github/workflows/continuous-integration-deb11.yml, .github/workflows/continuous-integration-deb12.yml, Cargo.toml, Dockerfile_deb11, Dockerfile_deb12, Makefile, src/serde_utils.rs
=> [tech] Update crates
