- Cargo.toml
- src/gtfs/read.rs
- src/objects.rs
- src/utils.rs
Fix #97 and compatibility with several contributors
> improve contributors compatibility

- fixtures/merge-ntfs/physical_modes.txt
- src/collection.rs
- src/model.rs
Before merge was crashing if there were 2 identical physical modes
Now
physical_mode_id|physical_mode_name
---|---
Bus|Bus
Metro|Metro
RapidTransit|Rapid Transit
merged with 
physical_mode_id|physical_mode_name
---|---
Bus|Bus
Metro|Metro
Funicular|Funiculaire
Train|Train
Tramway|Tramway
result
physical_mode_id|physical_mode_name
---|---
Bus|Bus
Metro|Metro
RapidTransit|Rapid Transit
Funicular|Funiculaire
Train|Train
Tramway|Tramway
> [Merge ntfs] Do not merge if there are 2 same physical modes

- src/bin/gtfs2ntfs.rs
- src/bin/merge-ntfs.rs
- src/bin/merge-stop-areas.rs
- src/bin/netex2ntfs.rs
- src/bin/ntfs2gtfs.rs
- src/bin/ntfs2ntfs.rs
- src/bin/transfers.rs
- src/common_format.rs
- src/gtfs/write.rs
- src/merge_stop_areas.rs
- src/netex/read.rs
- removed `warning: unused `#[macro_use]` import` after upgrading to rustc 1.30.0
- minor fixes
> Removed some warnings + minor fixes

- fixtures/apply_rules/complementary_codes_rules.txt
- fixtures/apply_rules/output/object_codes.txt
- fixtures/apply_rules/output/report.json
- src/apply_rules.rs
- src/bin/apply-rules.rs
- src/gtfs/write.rs
- src/lib.rs
- src/ntfs/write.rs
- src/test_utils.rs
- src/utils.rs
- tests/apply_rules.rs
- tests/merge_stop_areas.rs
- tests/read_ntfs.rs
Add object codes to line, route, stop_point, stop_area with a configuration csv file
Ex : complementary_codes_rules.txt
```csv
object,object_id,system_name,system_code
line,RERA,OSM,Relation:3195542
line,RERA,OSM,Relation:3224933
route,B42F,OSM,Relation:3187722
route,B42B,OSM,Relation:3187723
stop_point,GDLR,OSM,Node:1681252530
stop_area,CDG,OSM,Node:1730401509
```
`./target/release/apply-rules  -i . -c complementary_codes_rules.txt  -o output -r report.json`
`report.json` will contains 2 warnings
- **ComplementaryCodeRulesRead** if the csv is invalid
- **ComplementaryObjectNotFound** if an object is not found
ex `report.json`
```json
{
"errors": [],
"warnings": [
{
"category": "ComplementaryCodeRulesRead",
"message": "Error reading \"complementary_codes_rules2.txt\": CSV deserialize …
```
> Added apply-rules

- src/ntfs/read.rs
Previoulsy the copy to invert the stop_time_ids was done for every
comments, so it's a bit slow. This do it only one time to speed it.
This can be improved by doing the copy lazily to not pay the cost if
there isn't any comments on stop_times
> Improve performance when handling comments on stop_times

- src/objects.rs
it will make the transiberian handling for https://github.com/etalab/transpo-rt/pull/32
I plan to create a `DateTime` from the `Time` + a `Date` with: 
`date.and_time(chrono::NaiveTime::from_hms(0, 0, 0))
+ chrono::Duration::seconds(time.total_seconds() as i64)`
> make total seconds public to ease use

- fixtures/merge-ntfs/input/commercial_modes.txt
- src/bin/merge-ntfs.rs
- src/collection.rs
- src/gtfs/read.rs
- src/model.rs
- src/objects.rs
- src/read_utils.rs
- tests/merge_ntfs.rs
Problem: when we convert 2 GTFS to NTFS and merge them,  we can have 2 same commercial mode, for example "Bus" with 2 different ids.
We decided with @prhod and @papailio to normalize commercial modes and not add prefix on it
> [gtfs2ntfs] remove commercial mode prefix

- src/documentation/read_ntfs_fares.md
First version of reading NTFS fares, coupled with the current version of writing (and the version of the internal model).
> Doc Fares: added specs for reading NTFS fares

- src/documentation/write_ntfs_fares.md
First version of specs for writing NTFS fares (provided that at this stage, the NTFS fares model is far richer than the internal fares model).
> Doc Fares: added specs for writing NTFS fares

- model-builder/Cargo.toml
- model-builder/src/builder.rs
gives a better name ("transit_model_builder") to the model-builder before publishing it to crates.io
when this pr is merged would it be possible to publish the crates to crates.io ?
I don't think it will be mage automatically with the travis deploy
> rename model builder to publish it to crates.io

- Cargo.toml
- fixtures/apply_rules/input/lines.txt
- fixtures/apply_rules/input/networks.txt
- fixtures/apply_rules/output/geometries.txt
- fixtures/apply_rules/output/lines.txt
- fixtures/apply_rules/output/report.json
- fixtures/apply_rules/output/trips.txt
- fixtures/apply_rules/property_rules.txt
- src/apply_rules.rs
- src/bin/apply-rules.rs
- src/objects.rs
- src/utils.rs
- tests/apply_rules.rs
add the possibility to change some properties on NTFS lines
- line_name
- line_code
- line_color
- line_text_color
- forward_line_name
- backward_line_name
- forward_direction
- backward_direction
- line_sort_order
- physical_mode_id
- commercial_mode_id
- network_id
- line_geometry
> apply-rules on lines

- Dockerfile
I refactor entirely the `Dockerfile` because of the new presence of Proj.4. Before, the `Dockerfile` was based on a `scratch` version which was very light with embedded binary and only the binaries. But now, we need a dynamic link with Proj.4 llibrary so this strategy is not possible anymore.
> ND-213 - Add kv12ntfs binary to docker's image

- .travis.yml
- Cargo.toml
fix `use of undeclared type or module `transit_model_builder` in rust beta
needed to make test passed
> fix model-builder doc test in beta

- src/documentation/ntfs_fare_conversion_v2_to_V1.md
Only the two use cases needed for the moment.
> Doc: Conversion of V2 fares into V1 model

- src/documentation/nl_hellogo_fares_read.md
And one more question we could document too:
In `ServiceFrame/scheduledStopPoints`, if two `ScheduledStopPoints` (different or not) have the same `id`, which are we supposed to use? First one? Or we consider the whole thing invalid and dump the corresponding Ticket Use Restriction (and then maybe in chain the corresponding Ticket).
Note: I'm asking the question because it is a case that was present in the fixture that Nicolas and Virginia did for the fares v1.
**Update** I discussed about that question with @papailio and the answer is: the file is considered corrupted so we ignore it.
> Improve documentation for HelloGo fares conversion to NTFS fares

- fixtures/apply_rules/output_report/report_apply_complementary_codes.json
- fixtures/apply_rules/output_report/report_apply_property.json
- fixtures/apply_rules/output_report/report_consolidation_with_object_code.json
csv's error messages changed with version 1.1.0 but I don't know why
`record 8 (line: 9, byte: 278)` (see diff) was already there in the error msg
https://github.com/BurntSushi/rust-csv/compare/1.0.0...1.1.0#diff-9a269209bed069ffb36d5565a91c9840R204
> Fix output fixtures

- src/kv1/read.rs
- src/lib.rs
- src/objects.rs
- src/wgs84.rs
This trait will be used in the coming implementation of NaPTAN parsing too so it's not a one-shot trait.
> Add WGS84 trait for objects that can expose WGS84 coordinates

- src/transxchange/naptan.rs
Whenever a Stop Point is parsed from NaPTAN dataset which doesn't have a corresponding Stop Area (through `StopsInArea.csv`), we need to create a Stop Area (needed for NTFS) based on the Stop Point information (derived ID, name and coordinates).
> Create Stop Areas for Stop Points missing one

- fixtures/transxchange2ntfs/input/transxchange/simple.xml
- fixtures/transxchange2ntfs/output/ntfs/companies.txt
- src/transxchange/read.rs
This will get the operator reference from `<Service>` in order to generate the Network.
For companies, all `Operator` will generate a new company.
> Support for multiple networks and companies

- src/gtfs/mod.rs
- src/gtfs/read.rs
- src/kv1/mod.rs
- src/read_utils.rs
- src/transxchange/read.rs
[`read_config`](https://github.com/CanalTP/transit_model/compare/master...woshilapin:read_config?expand=1#diff-a5ae51324be0fd74d0e1e9788b025f85R45) function is not designed to create multiple Contributors or Datasets from a `config.json` but only one of each. So there is no reason the signature of this function returns `CollectionWithId`.
NB: This modification will be useful in the TransXChange convertor implementation.
> Make 'read_config' return unique contributor/dataset

- src/test_utils.rs
Using an ordered structure will help to understand what's going on when a test is failing. Below is an example of the exact same test with the same error but one with the `HashSet` (the code today) and one with `BTreeSet` (the proposition of this PR).
Much easier to understand what's going on in the second case.
> Use an ordered comparison structure to facilitate diff

- Cargo.toml
- src/gtfs/mod.rs
- src/kv1/mod.rs
- src/read_utils.rs
we think that requesting an url to get an archive can be done out of `transit_model`.
`read_url` uses `reqwest` that includes a lot of dependencies. Removing `reqwest` could lighten the build.
@antoine-de, @Tristramg do you use `read_url`?
reqwest dependencies 
```
├── reqwest v0.9.20
│   ├── base64 v0.10.1
│   │   └── byteorder v1.3.2 (*)
│   ├── bytes v0.4.12
│   │   ├── byteorder v1.3.2 (*)
│   │   ├── either v1.5.2
│   │   └── iovec v0.1.2
│   │       └── libc v0.2.60 (*)
│   ├── cookie v0.12.0
│   │   ├── time v0.1.42 (*)
│   │   └── url v1.7.2
│   │       ├── idna v0.1.5
│   │       │   ├── matches v0.1.8
│   │       │   ├── unicode-bidi v0.3.4
│   │       │   │   └── matches v0.1.8 (*)
│   │       │   └── unicode-normalization v0.1.8
│   │       │       └── smallvec v0.6.10
│   │ …
```
> removed read_url utility and reqwest crate 

- .travis.yml
The build in TravisCI is crashing a lot because of some timeout during the cache loading.  I did try a build on TravisCI without cache to compare the build time and it doesn't seem like the build time is affected (or if it is, it's a little bit shorter in average).
I also took a look in serde project which doesn't seems to use `cache: cargo` (note however that their build time is much shorter).
[This blog post](https://levans.fr/rust_travis_cache.html) seems to propose an alternative solution. But removing `~/.cargo/registry` and `target/` from the cache basically remove everything from the cache. What's left is:
- `~/.cargo/bin` which are the binaries for `cargo` (so we might win a little by avoiding a reinstallation of Cargo)
- `~/.cargo/.crates.toml`, contains only extension to cargo …
> Remove cargo cache in TravisCI

- Cargo.toml
- README.md
- benches/apply_rules.rs
- benches/filter_ntfs.rs
- benches/read_gtfs.rs
- benches/read_kv1.rs
- benches/read_ntfs.rs
- benches/read_transxchange.rs
A proposition to bring some benchmarks in the project. This would not be run on CI (bench is still a nightly feature for now) but that could help to evaluate a solution or an optimization.
I didn't create a bench for every possible functions for which it might make sense. But this PR should set a sufficient base to write any new bench needed.
Below the results on my machine. Obviously, it's only interesting to do comparative run on the same machine (a before/after comparison in the same condition).
```
Running target/release/deps/apply_rules-c8e83e1dc1c838b0                                                                             [50/9464]
running 4 tests …
```
> Add benches

- src/hellogo_fares/read.rs
- src/hellogo_fares/utils.rs
- src/lib.rs
- src/netex_utils/mod.rs
Starting to move some `utils` out of hellogo fares in a separate module so we can use them in Netex IDF. This PR is only a start (to keep the PR small), I'm also working on getting more in this `utils` module (like stuff about the frames).
> Create netex_utils module with 'get_value_in_keylist'

- src/kv1/read.rs
As I was working on `FileHandler`, I noticed these unused generic parameters... I've reported a bug to `clippy` about that https://github.com/rust-lang/rust-clippy/issues/4610.
> Remove unused generic declarations

- src/merge_stop_areas.rs
- tests/fixtures/merge-stop-areas/output/routes.txt
- tests/merge_stop_areas.rs
with `merge-stop-areas`, some stop areas are removed but routes referencing those stop areas in `destination_id` were not updated
> [fix] merge-stop-areas: update route's destination_id

- src/hellogo_fares/read.rs
- src/hellogo_fares/utils.rs
- src/netex_idf/lines.rs
- src/netex_idf/stops.rs
- src/netex_utils/mod.rs
- tests/enrich_with_hellogo_fares.rs
This PR is relatively big so we could do a live peer review so I can guide some of you to review it. Below is some details about what is done.
In HelloGo Fares, we had some utilities to parse Netex frames (`ServiceFrame`, `ResourceFrame`, `FareFrame`), classify them and use them. We have the same need in Netex IDF: this PR is mostly moving these utilities inside `netex_utils/mod.rs` and use these exposed methods in `netex_idf` parsing... with some adjustments :wink:
> Refactor of FrameType

- src/lib.rs
- src/ntfs/mod.rs
- tests/fixtures/filter_ntfs/output_extract/feed_infos.txt
- tests/fixtures/filter_ntfs/output_remove/feed_infos.txt
- tests/fixtures/gtfs2ntfs/minimal/output/feed_infos.txt
- tests/fixtures/gtfs2ntfs/minimal_with_config/output/feed_infos.txt
- tests/fixtures/kv12ntfs/output/feed_infos.txt
- tests/fixtures/merge-ntfs/output_feedinfos/feed_infos.txt
- tests/fixtures/merge-stop-areas/output/feed_infos.txt
- tests/fixtures/netexidf2ntfs/output/feed_infos.txt
- tests/fixtures/restrict-validity-period/output/feed_infos.txt
- tests/fixtures/transxchange2ntfs/output/ntfs/feed_infos.txt
We are currently on version 0.9.2.
Next version will be 0.10.0 with the field "trip_short_name_at_stop" (see https://github.com/CanalTP/ntfs-specification/blob/master/ntfs_changelog_fr.md)
There will never be version 0.9.3.
> Fix NTFS version

- .travis.yml
- Cargo.toml
Define the workspace. Will be useful for CanalTP/transit_model#406 and the `--all` option.
> Improve workspace and version definition

- src/documentation/common.md
- src/documentation/data_prefix.md
- src/documentation/gtfs_to_ntfs_specs.md
I added the specs on reading calendars and I modified the file data_prefix.md to common.md where I put together the common parts for all converters: for now, the specs on data prefix and datasets/contributors.
Eventually, santizer will be part of this file too.
> Specs gtfs2ntfs: reading calendars & common pre-processing

- .travis.yml
- CONTRIBUTING.md
This is an update related to the new version Rust 1.39 released on 07/10/2019. See https://github.com/rust-lang/cargo/pull/7241/. Interesting note: it seems this doesn't work for `cargo fmt` which still takes `--all` argument and doesn't accept `--workspace`.
> Remove --all [deprecated] in favor of --workspace

- Cargo.toml
So far, all of our released crates contained a lot of useless files, particularly all the fixtures files. This `package.exclude` should remove all useless files during the publishing process.
> Exclude all useless files from the Cargo publishing process

- src/gtfs/mod.rs
- src/gtfs/read.rs
- src/kv1/mod.rs
- src/lib.rs
- src/netex_idf/offers.rs
- src/read_utils.rs
- src/transxchange/read.rs
- src/validity_period.rs
Dear reviewers,
I'm curious about your opinion on moving `crate::objects::ValidityPeriod` into the new modules `crate::validity_period`?
> Extract validity_period's related function into it's own module

- src/apply_rules/complementary_code.rs
- src/apply_rules/mod.rs
- src/apply_rules/network_consolidation.rs
- src/apply_rules/property_rule.rs
I just moved some functions into submodules because `appy_rules.rs` was big. This is the same code.
It will allow me to do my next PR on apply_rules
> [tech] Moved apply_rules functions into modules

- Cargo.toml
We closed #458 since we want to let each contributor bump the version as they need to. But we need to catch up from the last version `0.11.0` (we've already produced code since and the version has not been bumped since).
Usually, I would have bumped to `0.11.1` but I believe the PR #455 is breaking change (we're changing from NTFS `v0.9.2` to NTFS `v0.10.0`.
> [tech] Bump version to catch up on our new strategy (see #458)

- src/netex_idf/lines.rs
Structure Line/RepresentedByGroupRef/@ref can not exist. It is not an obligatory field, and according to specifications the line should be skipped.
> [fix] Netex - Skip line without network

- Cargo.toml
- model-builder/README.md
- src/lib.rs
This Model Builder is only partial (it doesn't allow the creation of networks and lines for example). The problem is that we have ongoing work to sanitize automatically the `Model` on creation (in the `new()` method) which means that all the tests are breaking because a model that have `stop_times` which are not linked to a `line` are now sanitized...
Ping @antoine-de
> Deprecate model-builder crate

- src/lib.rs
- src/netex_france/exporter.rs
- src/netex_france/mod.rs
- tests/write_netex_france.rs
Just a skeleton for the exporter. Trying something new in term of architecture with a `struct` (instead of a function) that will own the `Model` and be responsible for the export. The reason is that we discussed a lot of possible parameters to pass to the binary; the `Exporter` is the structure that would also have these parameters.
Note: Putting that PR as a Draft for now. Please tell me what you think of it.
> [tech] Skeleton for the Netex France exporter

- src/test_utils.rs
An attempt to fix 2 problems with the XML comparison test utils. First of all, as you can see below, the diff from `pretty_assertions` does color the difference but it is just a huge green `String`. Separation per line would be helpful.
On top of that, the XML file we're dealing with in `transit_model` are relatively big, and therefore, comparing 2 `String` that huge is quiet process intensive. The result is:
- when the test pass, the result appears right away
- when the test fails, the result might take a few dozen of seconds before generating the colored diff to print
What I changed here is to do a difference line by line. Here is what it would look like.
> [tech] Fix full content comparison in test_utils

- src/documentation/ntfs_to_netex_france_specs.md
I copy/pasting an example here of a `calendar.txt` and a `calendar_dates.txt`, as well as the expected results in `calendriers.xml`.
```csv
service_id,monday,tuesday,wednesday,thursday,friday,saturday,sunday,start_date,end_date
service_one,0,0,0,0,0,1,1,20190710,20190720
```
```csv
service_id,date,exception_type
service_one,20190714,1
service_one,20190715,0
service_two,20191225,0
```
```xml
<?xml version="1.0" encoding="UTF-8"?>                          
<PublicationDelivery
version="1.09:FR-NETEX_LIGNE-2.1-1.0"
xmlns="http://www.netex.org.uk/netex"
xmlns:core="http://www.govtalk.gov.uk/core"
xmlns:gml="http://www.opengis.net/gml/3.2"
xmlns:ifopt="http://www.ifopt.org.uk/ifopt"
xmlns:siri="http://www.siri.org.uk/siri"
xmlns:xlink="http://www.w3.org/1999/xlink" …
```
> [doc] Add specifications for calendriers.txt

- Cargo.toml
- src/ntfs/write.rs
- tests/gtfs2ntfs.rs
The test `tests/gtfs2ntfs.rs::test_gtfs_with_levels` is already testing if we're writing correctly the `StopLocation` (type `3`, `4` and `5`).
> [feature] Support StopLocation write by default

- Cargo.toml
- src/documentation/ntfs_to_netex_france_specs.md
- src/netex_france/calendars.rs
- src/netex_france/exporter.rs
- src/netex_france/stops.rs
- tests/fixtures/netex_france/input_gtfs/stops.txt
- tests/fixtures/netex_france/input_ntfs/equipments.txt
- tests/fixtures/netex_france/input_ntfs/stops.txt
- tests/fixtures/netex_france/output/arrets.xml
> [feature] NeTEx France - Add AccessibilityAssessment on Quays

- transit_model_procmacro/Cargo.toml
The build of `transit_model` is broken on `master` branch. We waited a little bit too long for merging the PR on tests for `procmacro` (#412) and we missed a problem with the new versions of `syn` and/or `quote`: their versions are way too old and we're starting to see problems related to incompatibilities of some libraries using more recent versions. Now that we have tests around this macro, we should be able to upgrade them more safely (still need some complex work though).
This PR should fix the build in the meantime.
> [tech] Fix build of 'transit_model_procmacro

- Cargo.toml
- collection/Cargo.toml
- collection/src/collection.rs
- src/gtfs/read.rs
- src/kv1/read.rs
- src/lib.rs
- src/netex_idf/lines.rs
- src/objects.rs
Waiting for https://github.com/CanalTP/transit_model/pull/571 to be merged in order to fix the build.
> [tech] Move 'impl_id' inside the 'transit_model_collection' crate

- src/apply_rules/property_rule.rs
- src/common_format.rs
- src/gtfs/mod.rs
- src/gtfs/read.rs
- src/gtfs/write.rs
- src/kv1/read.rs
- src/netex_france/stops.rs
- src/netex_idf/accessibility.rs
- src/ntfs/mod.rs
- src/objects.rs
Waiting for https://github.com/CanalTP/transit_model/pull/571 to be merged in order to fix the build.
> [tech] Move Availability from 'common_format' to 'objects'

- Cargo.toml
- src/kv1/mod.rs
- src/kv1/read.rs
Modification of how `kv1::read` works: it uses a `Path` instead of `FileHandler` structure. `read_from_zip()` now unzip all the files into a temporary folder and call `read_from_path()` with this temporary folder.
> [tech] Remove FileHandler from 'kv1' module

- src/gtfs/mod.rs
- src/gtfs/read.rs
- src/kv1/mod.rs
- src/lib.rs
- src/netex_idf/offers.rs
- src/transxchange/read.rs
- src/validity_period.rs
I've modified the name of the methods:
- `set_dataset_validity_period()` into `calculate_dataset_validity_period()` because it does calculate a validity period out of the list of `Calendar`
- `update_validity_period()` into... `set_dataset_validity_period()` because it takes a mutable `Dataset` and a `ValidityPeriod` and set it, just like that!
> [tech] Expose new API validity_period

- Cargo.toml
- src/kv1/mod.rs
`tempfile` is integrated into the `tempfile` crate (as mentioned in the documentation of `tempdir`). So let's try to remove `tempdir` from our dependencies.
> [tech] Replace 'tempdir' with 'tempfile'

- src/read_utils.rs
Every time we run test, this block of documentation is considered as a test, but ignored. But in reality, this is only some documentation block, not even Rust code. The `text` is more appropriate than `ignore`.
> [tech] Replace 'ignore' by 'text' for JSON documentation

- src/lib.rs
Follow up of the PR https://github.com/CanalTP/transit_model/pull/582.
> [feature] Expose publicly 'calendars' (fixes #582)

- src/documentation/netex_idfm_to_ntfs.md
Looks like a typo when updating the specs
> [doc] Fix commercial_mode_id for interregionalRail

- .github/workflows/publish.yml
The current `publish` workflow can't work because the compilation (done during publishing) needs `proj`. ~Also, I believe the tests are ran during publish so `xmllint` must be installed as well as NeTEx submodules checkout.~ The tests are [not done during publish](https://doc.rust-lang.org/cargo/reference/publishing.html#packaging-a-crate), removing checkout of submodules and installation of package `libxml2-utils`.
> [fix] Fix the auto-publish Github Actions

- Cargo.toml
- src/model.rs
Needed for moving `merge-ntfs` into `tartare-tools`. It would be possible to move `merge-ntfs` without exposing these constants (so not a big deal if we don't do it) but it felt nice to actually expose the list of official supported Physical Modes.
> [feature] Expose Physical Mode constants

- Cargo.toml
The PR https://github.com/CanalTP/minidom_ext/pull/4 broke the `master` branch of `transit_model`.
> [tech] Update minidom to 0.12

- .github/workflows/ci.yml
- Cargo.toml
- gtfs2netexfr/Cargo.toml
- gtfs2ntfs/Cargo.toml
- ntfs2gtfs/Cargo.toml
- ntfs2netexfr/Cargo.toml
- ntfs2ntfs/Cargo.toml
`clippy::cargo` is not enabled by default but can provide some useful hints on  `Cargo.toml` manifests. However, there is no easy way to solve the problem of multiple versions of dependencies so I specifically deactivated this one.
> [lint] Fix some clippy warnings on Cargo manifests

- src/gtfs/read.rs
- src/gtfs/write.rs
- src/model.rs
- src/ntfs/filter.rs
- src/ntfs/mod.rs
- src/ntfs/read.rs
- src/ntfs/write.rs
- tests/read_ntfs.rs
Reverts CanalTP/transit_model#623
> Revert "[tech] use of ids instead of indexes for stop_times optional fields"

- Cargo.toml
No configuration defaults to the default features which, in our case is no feature. This should remove the `proj` feature and fix the build of our documentation on `docs.rs` (see https://docs.rs/crate/transit_model/0.17.2/builds/246776).
> [doc] Fix doc build on docs.rs (remove 'proj' feature)

- Cargo.toml
- src/apply_rules/complementary_code.rs
- src/apply_rules/mod.rs
- src/apply_rules/network_consolidation.rs
- src/apply_rules/property_rule.rs
- src/lib.rs
- src/merge_stop_areas.rs
- src/report.rs
- src/transfers.rs
- src/utils.rs
For moving some part of `transit_model` like `apply_rules` out of `transit_model`, we need to expose `Report` and `ReportType`.  However, some variant enums of `ReportType` are really related to `apply_rules` itself, not to `transit_model`. So I changed `ReportType` into a trait/contract/interface instead of an `enum`. User needs to implement a type that conforms to this contract. I also moved `Report` and `ReportType` into their own module `report`.
See https://github.com/CanalTP/tartare-tools/pull/77 for how this new trait will be used.  In the current PR, one implementation of the new trait `ReportType` is `TransitModelReportType` which is nothing else than the old `enum ReportType`.
> [feature] Expose Report and ReportType

- src/gtfs/read.rs
- src/gtfs/write.rs
- src/model.rs
- src/netex_france/offer.rs
- src/netex_france/route_points.rs
- src/netex_idf/offers.rs
- src/ntfs/mod.rs
- src/ntfs/read.rs
- src/objects.rs
I'm targetting a `stop-time` branch for now. We'll merge everything once the whole work on `StopTime` is done. It will allow us to split the work in smaller chunks.
This PR is only introducing the fields inside `objects::StopTime`, not filling them for now.
Next steps will be to fix module one by one until we can remove the `HashMap` in `Collections`: `stop_time_ids`, `stop_time_headsigns` and `stop_time_comments`.
> [tech] Introduce ID, headsign and comments inside StopTime

- CONTRIBUTING.md
- README.md
- documentation/ntfs_to_netex_france_specs.md
- gtfs2netexfr/README.md
- gtfs2ntfs/README.md
- ntfs2gtfs/README.md
- ntfs2netexfr/README.md
- replaced `<br>` by `\` https://github.github.com/gfm/#example-658
> [doc] no inline html in markdown

- .travis.yml
- CONTRIBUTING.md
- README.md
- gtfs2netexfr/README.md
* Consistency on how `clippy` and `test` are checked
* Word on our environments and tools
This work is debatable.
A future PR should attempt to use cargo (and maybe makefile) to minimize/centralize commands to type.
Ref. ND-930
> [doc] Improve contributing

- gtfs2netexfr/src/main.rs
- gtfs2ntfs/README.md
- gtfs2ntfs/src/main.rs
- ntfs2gtfs/README.md
- ntfs2gtfs/src/main.rs
- ntfs2netexfr/README.md
- ntfs2netexfr/src/main.rs
- ntfs2ntfs/README.md
- ntfs2ntfs/src/main.rs
- restrict-validity-period/README.md
> [doc] Improve documentation for binaries

- Cargo.toml
Upgrade non-geo dependencies (those are tricky will come in later PR).
Also remove useless dep (tested `cargo udeps`).
TODO:
> [tech] Upgrade simple deps

- .github/workflows/ci.yml
- .travis.yml
- CONTRIBUTING.md
- Makefile
- README.md
Centralize in makefile and expose in doc and CI
Also:
* rm system package for install_proj (+ comments and cosmetic refactor)
* minor doc update after update on TT (https://github.com/CanalTP/tartare-tools/pull/103#discussion_r451521210)
TODO:
Ref. ND-947
> [tech] [doc] Centralize fmt, clippy & test in makefile

- Cargo.toml
- gtfs2netexfr/Cargo.toml
- gtfs2ntfs/Cargo.toml
- ntfs2gtfs/Cargo.toml
- ntfs2netexfr/Cargo.toml
- ntfs2ntfs/Cargo.toml
- restrict-validity-period/Cargo.toml
- src/model.rs
- tests/fixtures/restrict-validity-period/output/routes.txt
Auto-generate `route.destination_id` always (it was auto-generated only when `route.name` was empty).
ref: ND-916
> [feature] Auto-generate route.destination_id if missing

- documentation/gtfs_to_ntfs_specs.md
- src/gtfs/read.rs
- tests/fixtures/gtfs2ntfs/minimal/output/routes.txt
- tests/fixtures/gtfs2ntfs/no_traffic/output/routes.txt
- tests/fixtures/netex_france/input_ntfs/routes.txt
- tests/fixtures/netex_france/output/reseau_TheGreatNetwork_1e97c33560621530a594ced114597ea1/offre_MagicBus_23cdf50ee73fcba0d38beca2d8cc8c0e.xml
- tests/fixtures/netex_france/output/reseau_TheGreatNetwork_1e97c33560621530a594ced114597ea1/offre_f31e1eef20f64733a18c538073e78396.xml
When creating a Route, we want to apply generic `route_name` generation unless all trips in that route are in the same direction, in this case, we keep the route's name.
Bonus: The specification proposes to use `route_short_name` if `route_long_name` is empty but our previous implementation was only using `route_long_name`. This PR fixes it.
ref: ND-681
> [feature] Improve route_name generation in GTFS parsing

- Cargo.toml
- gtfs2netexfr/Cargo.toml
- gtfs2ntfs/Cargo.toml
- ntfs2gtfs/Cargo.toml
- ntfs2netexfr/Cargo.toml
- ntfs2ntfs/Cargo.toml
- restrict-validity-period/Cargo.toml
- src/add_prefix.rs
- src/gtfs/mod.rs
- src/gtfs/read.rs
- src/lib.rs
- src/objects.rs
Evolution of the `AddPrefix` trait in order to be able to prefix with more information. This evolution is needed for merging together objects of the same contributors that might have the same identifier but are different objects from `transit_model` point-of-view (for example, a `VehicleJourney` that would share the same identifier for the winter service and the summer service).
ref: ND-964
> [feature] AddPrefix can prefix referential or scheduled objects

- Cargo.toml
- src/objects.rs
- tests/fixtures/gtfs2ntfs/full_output/equipments.txt
- tests/fixtures/gtfs2ntfs/full_output/stops.txt
Equipments being auto-generated it is preferable to use the schedule_prefix (instead of referential_prefix) to avoid erroneous assignments to stop_points during a merge.
Ref. ND-980
> [feature] Use schedule_prefix for equipment

- documentation/common_ntfs_rules.md
- documentation/gtfs_to_ntfs_specs.md
Update gtfs2ntfs specifications with the introduction of the sub-prefix in some identifiers (in release https://github.com/CanalTP/transit_model/releases/tag/v0.25.0)
Ref. ND-981
> [tech] Update gtfs2ntfs specification

- src/model.rs
- tests/fixtures/restrict-validity-period/output/comment_links.txt
Schedule objects are not handled, as no merge is done for them (duplicates would only be the result of initial data).
Ref. ND-979
TODO:
> [feature] Full comment deduplication for referential objects, based on name only for similarity

- Makefile
fix two issues:
* `pushd` and `popd` are bash builtin commands (it does not work with dash for instance, which is the default shell on Ubuntu)
* each command line in a recipe is executed from the folder containing the `makefile`, changing the directory on the same line than running `./configure` is required
> fix installation of 'proj'

- README.md
- examples/README.md
- examples/gtfs_reader.rs
- examples/ntfs_crawler.rs
- src/model.rs
- src/utils.rs
- src/vptranslator.rs
- tests/read_ntfs.rs
fix https://github.com/CanalTP/transit_model/issues/329
Also some clippy-related work.
> [doc] improve examples

- Cargo.toml
By default the crate `zip` uses features
- deflate
- bzip2 (bindings to libbz2)
- time
We don't use bzip2 and time.
> [tech] only use deflate feature of crate zip

- src/objects.rs
No need to parse since we already know the enum variant to use.
> [fix] Give expected enum instead of using 'parse()'

- .github/workflows/ci.yml
* It visually breaks on vulnerabilities, in forks or not
* It does **not** block merging a PR (`continue-on-error: true` as I think we might end up with some vulnerabilities that we could not immediately deal with, and that are sometimes out of our reach : deps of deps)
* It displays a nice report **only** on main-repo branches, not on forks (but console output is readable anyway)
* It does **not** visually output warnings (one have to search for the report or console output). And no `--deny-warning` available (not sure we would want it anyway as it might be too strict).
Current warnings (no vulnerabilities):
* failure is deprecated/unmaintained (already identified to be replaced)
* term (brought by slog-term) is looking for maintainer since end of 2018
--Comment heavily updated--
> [tech] Use action-rs/audit-check

- Cargo.toml
- src/gtfs/read.rs
- src/lib.rs
- src/model.rs
- src/read_utils.rs
This small PR takes inspiration from [this little tip](https://octodon.social/@rust/104670964806314333).
**Note -** This is not a breaking change even if we change the type `transit_model::Result` which is part of our API.
> [feature] Make transit_model::Result generic on Error

- src/test_utils.rs
Historically, in our `test_utils` framework, we test the number of files produced vs the number of files in the fixture and compare them. This sometimes leads to something like this kind of error.
This is not very helpful. So I changed it to a comparison of the 2 lists which would show something like this (more helpful I believe). Note that I used a `BTreeSet` instead of a `Vec` so the list is ordered and the diff much more helpful.
As a bonus, hidden files are also filtered. This was inconvenient when you're currently editing a file (like `transfers.txt`) because some editors like `vim` create a swap file (like `.transfers.txt.swp`).
> [feature] Improve test utils for report on files count

- Cargo.toml
- src/model.rs
- src/objects.rs
The Model can be cleaned up of comments without any text.
ref: ND-1003.
> [feature] Automatically remove empty comments from the model

- src/transfers.rs
- tests/fixtures/transfers/mono_contributor/input/stop_times.txt
- tests/fixtures/transfers/mono_contributor/input/stops.txt
When a `StopPoint` geolocation is `(0, 0)`, generating a transfer doesn't make sense and will create weird and incorrect behaviors. This PR prevent the creation of such transfers.
ref: ND-1016.
> [fix] Do not create transfers when geolocation is (0, 0)

- Cargo.toml
- gtfs2ntfs/Cargo.toml
- gtfs2ntfs/src/main.rs
- src/gtfs/read.rs
> [feature] warning if more than one timezone is reported on agency file

- Cargo.toml
For
- [fix] fix short option for gtfs2ntfs #704
- [feature] warning if more than one timezone is reported on agency file #705 
- [tech] Support last version of NeTeX norm #706
> [tech] Bump 0.31.3

- src/ntfs/read.rs
Follow-up of https://github.com/CanalTP/transit_model/pull/710#discussion_r502289262.
> [fix] Small syntax improvement instead of 'matches'

- src/model.rs
- src/objects.rs
- src/utils.rs
Change the parsing of `trip_headsign` so when the `String` is empty, it is transformed into `None`.
ref: ND-1112.
> [feature] Rebuild 'trip_headsign' if empty string

- documentation/gtfs_to_ntfs_specs.md
- examples/gtfs_reader.rs
- gtfs2netexfr/Cargo.toml
- gtfs2netexfr/src/main.rs
- gtfs2ntfs/Cargo.toml
- gtfs2ntfs/src/main.rs
- src/gtfs/mod.rs
- src/gtfs/read.rs
- tests/gtfs2ntfs.rs
- tests/write_netex_france.rs
> [feature] read gtfs route as line

- CONTRIBUTING.md
Some help about why and how we update versions of `Cargo.toml` files in the Pull Request.
> [doc] Update CONTRIBUTING about PR and versions

- Cargo.toml
- model-builder/Cargo.toml
- model-builder/src/builder.rs
- src/model.rs
- src/objects.rs
To keep to data as clean as possible, the model was sanitized to add restrictions on drop off at first stop time / pick up at last stop time.
Since for stay in this could remove valid journeys, the pick up at last stop time / drop off at first stop time was possible for stay in.
The previous implementation was removing explicitly set constraints on those stay in stop times.
As a side effect we now also correctly handle restrictions on stay in of different calendars (see [example 4](https://github.com/antoine-de/navitia_model/blob/fae185abe7d36cee8648ee45799853220466abd1/src/model.rs#L787-L796))
Note 1: the new implementation is quadratic in term of trip on the same `block_id`. However the number of vj on the same block_id seems quite limited thus the runtime penalty is quite small.
I …
> keep forbidden pickup/dropoff on stay in

- src/gtfs/read.rs
- tests/fixtures/gtfs2ntfs/routes_comments/input/agency.txt
- tests/fixtures/gtfs2ntfs/routes_comments/input/calendar_dates.txt
- tests/fixtures/gtfs2ntfs/routes_comments/input/routes.txt
- tests/fixtures/gtfs2ntfs/routes_comments/input/stop_times.txt
- tests/fixtures/gtfs2ntfs/routes_comments/input/stops.txt
- tests/fixtures/gtfs2ntfs/routes_comments/input/trips.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/calendar.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/comment_links.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/comments.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/commercial_modes.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/companies.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/contributors.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/datasets.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/feed_infos.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/lines.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/networks.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/object_codes.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/physical_modes.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/routes.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/stop_times.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/stops.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/trips.txt
- tests/gtfs2ntfs.rs
Internal issue: https://jira.kisio.org/browse/ND-1075
> gtfs2ntfs: read route_desc into comments

- Cargo.toml
- src/enhancers/enhance_co2.rs
- src/enhancers/fill_co2.rs
- src/enhancers/mod.rs
- src/lib.rs
- src/model.rs
This is the first step to split `model.rs` into several files to improve maintanability.
To ease review I think you can review this and if it's ok we can merge and do separate PR
> [tech] move the enhance co2 function out of the model

- src/gtfs/mod.rs
- src/read_utils.rs
closes https://github.com/CanalTP/transit_model/issues/737
Add a `gtfs::from_read` method to be able to read gtfs from various
sources (like from the network).
this makes it possible to read a gtfs like
```rust
let url = "http://some_url/gtfs.zip";
let resp = reqwest::blocking::get(url)?; // or async call
let data = std::io::Cursor::new(resp.bytes()?.to_vec());
let model = transit_model::gtfs::from_read(data, &url, configuration)?;
```
> add a gtfs::from_read method

- documentation/gtfs_to_ntfs_specs.md
- src/gtfs/read.rs
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/calendar.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/comment_links.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/comments.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/commercial_modes.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/companies.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/contributors.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/datasets.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/feed_infos.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/lines.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/networks.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/object_codes.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/physical_modes.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/routes.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/stop_times.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/stops.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/trips.txt
- tests/gtfs2ntfs.rs
> handle route comments on line when using read_as_line

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- Dockerfile
- Makefile
- README.md
- src/netex_france/exporter.rs
Use now the custom image that already contains `rustfmt`, `clippy`,`cargo-audit` and `libproj`. This should improve the build time and make it more reliable with `libproj` since we're not depending anymore on the custom `.deb`.
> [ci] use 'rust-ci:latest-proj'

- Cargo.toml
Just some documentation to keep track of why we ought to not upgrade to `minidom:0.13.0`.
> [tech] do not upgrade to minidom:0.13.0

- Cargo.toml
- gtfs2netexfr/Cargo.toml
- gtfs2netexfr/src/main.rs
- gtfs2ntfs/Cargo.toml
- gtfs2ntfs/src/main.rs
- ntfs2gtfs/Cargo.toml
- ntfs2gtfs/src/main.rs
- ntfs2netexfr/Cargo.toml
- ntfs2netexfr/src/main.rs
- ntfs2ntfs/Cargo.toml
- ntfs2ntfs/src/main.rs
- src/lib.rs
- src/version_utils.rs
usefull for workflows depending directly of the git repository
seems to handle well the incremental compilation:
```sh
❯ cargo build --all
Compiling transit_model v0.34.0 (/home/antoine/dev/kisio/transit_model)
Compiling ntfs2gtfs v1.1.0 (/home/antoine/dev/kisio/transit_model/ntfs2gtfs)
Compiling transit_model_builder v0.3.0 (/home/antoine/dev/kisio/transit_model/model-builder)
Compiling restrict-validity-period v1.0.0 (/home/antoine/dev/kisio/transit_model/restrict-validity-period)
Compiling gtfs2ntfs v1.1.0 (/home/antoine/dev/kisio/transit_model/gtfs2ntfs)
Compiling gtfs2netexfr v1.1.0 (/home/antoine/dev/kisio/transit_model/gtfs2netexfr)
Compiling ntfs2ntfs v1.0.0 (/home/antoine/dev/kisio/transit_model/ntfs2ntfs)
Compiling ntfs2netexfr v1.0.0 …
```
> add a precise git_version to transit-model

- Cargo.toml
- gtfs2netexfr/Cargo.toml
- gtfs2ntfs/Cargo.toml
- ntfs2gtfs/Cargo.toml
- ntfs2netexfr/Cargo.toml
- ntfs2ntfs/Cargo.toml
- restrict-validity-period/Cargo.toml
- src/gtfs/mod.rs
- src/netex_france/exporter.rs
- src/ntfs/mod.rs
Long time standing issue that was creating cryptic error when trying to **write** a NTFS (and also a NeTEx France).
```
Error reading "/mnt/out/output_dir/feed_infos.txt"
No such file or directory (os error 2)
```
> [feature] automatically create output folders when not existing

- Cargo.toml
- model-builder/src/lib.rs
- src/lib.rs
- src/model.rs
Introduce a new function to mutate the model.
```rust
Model::add_calendar(
&mut self,
calendar: Calendar,
// Other parameters ?
)
```
> [feature] add 'Model::add_calendar' under 'mutable-model' feature

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- Dockerfile
After https://github.com/CanalTP/ci-images/pull/24 (needed before merge): less is more :tada: 
No difference in images available there anymore (stretch vs. buster), and all proj-work is done already.
> [tech] use latest ci-images

- .github/workflows/ci.yml
To avoid double-builds on PR (branch+PR)
Inspired by Kirin, but letting build on tags be launched (even though it's publish part that matters more, tests are nice to have)
> [CI] Limit branch-build to 'master'

- .github/workflows/ci.yml
- .github/workflows/publish.yml
- add notification for each job to slack in case `failure` and `master` branch
- add a Webhook secret in GitHub `SLACK_CORE_TOOLS_TEAM_URL`  : [here](https://github.com/CanalTP/transit_model/settings/secrets/actions)
- add a message text `global variable` in workflow
> [tech] add notification to slack

- Cargo.toml
- src/gtfs/read.rs
- src/read_utils.rs
Some possible use of `skip_error_and_log()` on `Iterator`. Depends on CanalTP/skip_error#9.
> [feature] use the new Iterator::skip_error

- src/model.rs
Using a `HashMap` to filter the `VehicleJourney` then iterating again over them makes the final order of `VehicleJourney` completely random compare to the input order. This is not really desirable for two reasons:
- why modifying the input order at all? I wouldn't think this would be expected from an end-user 
- running twice the same binary might actually produce 2 different orders due to the fact that `HashMap` is randomized at runtime: it might actually cause some problems for testing
Note that we're talking about `transit_model` library end-users (using `Model`). The binaries will also write the output files in different order but semantically, the model is still the same so it's not incorrect.
This modification should barely impact the performance since this is not really changing …
> [feature] keep the original order of vehicle journeys

- gtfs2netexfr/Cargo.toml
- gtfs2ntfs/Cargo.toml
- ntfs2gtfs/Cargo.toml
- ntfs2netexfr/Cargo.toml
- ntfs2ntfs/Cargo.toml
- restrict-validity-period/Cargo.toml
Having both `path` and `version` is useful only when the _crate_ is published. From the [documentation](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-path-dependencies), `path` is always used, except for `publish` where `version is used. Since we don't release these crates, versions are not needed.
NOTE: we also want to avoid a situation where we would publish a crate `gtfs2ntfs:0.36.1` with a dependency `transit_model:0.36.0` which would be possible with a dependency specified like `version = "0.36"`. Therefore, the rational here is that since we don't publish these crates at all, removing the version is a way to push back the problem to the day we will decide to do it (or not !).
> [feature] remove the versions (crates are unpublished)

- Cargo.toml
- Makefile
- README.md
- src/netex_france/offer.rs
- src/netex_france/stops.rs
- src/objects.rs
- src/utils.rs
I work on some of the libraries you use and wanted to see how some recent changes affect our users. 
Thought I might as well share the changes in case you'd like to update.
> update geo dependencies

- Makefile
Putting a comment at the end of the line makes the space after the version, part of the variable... which obviously breaks the URL afterwards (trying to download to `https://github.com/OSGeo/proj.4/releases/download/7.2.1 /proj-7.2.1 .tar.gz`). `make` is awesome!
> [fix] 'install_proj' in the Makefile now works as expected

- .github/workflows/ci.yml
There was a change of version of `cargo-tarpaulin` on the 28th of June. The new version doesn't accept `--all-targets` anymore so our CI fails. This PR should fix it.
> [ci] 'cargo-tarpaulin:v0.18.0' does not accept '--all-targets' anymore

- gtfs2ntfs/Cargo.toml
- gtfs2ntfs/src/main.rs
I'm opening this as a Draft for discussion. I really think we should convert all of `transit_model` (library and binaries) to `tracing` as it gives us some more capabilities without losing the support for `log`.
Let me know if you're OK that I continue converting the rest of `transit_model`. Probably can be done in multiple PR.
> [feature] convert 'gtfs2ntfs' to tracing

- Cargo.toml
- src/objects.rs
Using `thiserror` (already in our dependencies) to improve the definition of 2 existing errors (`RgbError` and `TimeError`). Note that they both were implementing [`description()` which is a deprecated function of the trait `std::error::Error`](https://doc.rust-lang.org/std/error/trait.Error.html#method.description). The modification is not strictly equivalent to what was existing before (because there is now no difference between the `Display` implementation and the associated error message). But I believe this is fine since `description()` should be implemented into `Display`.
> [feature] use 'thiserror' for the existing errors

- Cargo.toml
- gtfs2ntfs/src/main.rs
When `slog` was removed in #791, we lost the default level of logging: previous versions was defaulting to INFO, but `tracing` was logging nothing. This should bring back a default logging level at INFO.
Since the code for initializing the logger was a bit longer, I put all of it in a `init_logger()` function.
> [feature] default logs to INFO (was NONE)

- Cargo.toml
- src/calendars.rs
- src/gtfs/read.rs
- src/model.rs
- src/ntfs/read.rs
- src/read_utils.rs
- src/utils.rs
- tests/read_ntfs.rs
:heavy_check_mark: : waiting on CanalTP/skip_error#10 to be merged and released.
This PR does 2 things:
- use `skip_error:2.0.0`
- switch to the new feature `tracing` of `skip_error`
> [feature] use 'skip_error:2.0.0' with 'tracing'

- src/gtfs/read.rs
> [tech] Deduplicate gtfs stoptimes

- .github/workflows/dockerhub-publish.yml
Bad url (ok in local test) + rollback on `--password-stdin` to remove secure warning
> [fix] Fix Dockerhub login/push

- gtfs2netexfr/Cargo.toml
- gtfs2netexfr/src/main.rs
- gtfs2ntfs/src/main.rs
- ntfs2gtfs/Cargo.toml
- ntfs2gtfs/src/main.rs
- ntfs2netexfr/Cargo.toml
- ntfs2netexfr/src/main.rs
- ntfs2ntfs/Cargo.toml
- ntfs2ntfs/src/main.rs
- restrict-validity-period/Cargo.toml
- restrict-validity-period/src/main.rs
Brings `tracing` to all the binaries without printing an error message when `RUST_LOG` is missing (but will still produce an error message when `RUST_LOG` is invalid).
> [fix] RUST_LOG error message only when invalid

- Cargo.toml
- src/model.rs
- src/objects.rs
- tests/fixtures/netex_france/output/correspondances.xml
ref: https://jira.kisio.org/browse/ND-1572
The commit  https://github.com/CanalTP/transit_model/pull/786/commits/c93a60d9e0c6614d259a0fa0ea4474c6c778eb28 from https://github.com/CanalTP/transit_model/pull/786 deteriorates the performance. I reverted a part of the commit
ntfs2ntfs on a 132MB NTFS
Before > 23min, 2,1 GB Ram
After ~2 min, 3 GB Ram
> [fix] Revert dedup simplification

- Cargo.toml
- src/lib.rs
- src/ntfs/mod.rs
- tests/fixtures/gtfs2ntfs/full_output/feed_infos.txt
- tests/fixtures/gtfs2ntfs/minimal/output/feed_infos.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/feed_infos.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/feed_infos.txt
- tests/fixtures/restrict-validity-period/output/feed_infos.txt
`ntfs:v0.12.1` (compared to `v0.12.0`) introduce the possible value `3` in the fields `drop_off_type` and `pickup_type` of `stop_times.txt`. There is nothing much to do since these fields are implemented as `u8` (so the value `3` is already supported).
> [feature] support 'ntfs:v0.12.1'

- .github/workflows/ci.yml
It seems we have a problem with how `cargo tarpaulin` is called (see [here](https://github.com/CanalTP/transit_model/runs/4014256639?check_suite_focus=true)).
> [ci] fix how tarpaulin is called

- Cargo.toml
- src/ntfs/read.rs
This should make `transit_model::ntfs::read()` more resilient to incorrect comments (will be warned but won't make the function `panic`).
fixes #827
> [fix] do not panic on incorrect comments

- src/model.rs
- src/objects.rs
Ref. https://navitia.atlassian.net/browse/DATENG-34
> [feature] check coordinate validity

- ntfs2gtfs/src/lib.rs
- src/add_prefix.rs
- src/enhancers/enhance_pickup_dropoff.rs
- src/model.rs
Some useless allocation now that we have `CollectionWithId::indexes()` which doesn't keep a reference on the `CollectionWithId`.
> fix: remove useless allocations with '.indexes()'

- Cargo.toml
- src/enhancers/fill_co2.rs
- tests/fixtures/gtfs2ntfs/physical_modes/output/physical_modes.txt
ADEME made some update about the default values of CO2 per physical mode. See https://monimpacttransport.fr/.
ref: DATENG-337.
> feat: change default values for CO2

- Cargo.toml
I was trying to add more logs to my release build in loki, so I set 
```
tracing = { version = "0.1", features = ["log", "release_max_level_debug"] }
```
in my Cargo.toml. 
But to my surprise, I didn't get any `debug` level logs :dizzy_face: !
Some digging led me to the [log doc](https://docs.rs/log/latest/log/#compile-time-filters), that clearly says : 
> Libraries should avoid using the max level features because they’re global and can’t be changed once they’re set. 
Indeed, rust try to compiles a single version of `tracing` [when possible](https://doc.rust-lang.org/cargo/reference/resolver.html). 
In order to do so, it [unifies](https://doc.rust-lang.org/cargo/reference/features.html#feature-unification) all features of tracing requested by all dependencies.
So if `transit_model` …
> [tech] Remove max_release_level tracing feature in lib

- Cargo.toml
- gtfs2netexfr/Cargo.toml
- gtfs2ntfs/Cargo.toml
- ntfs2gtfs/Cargo.toml
- ntfs2netexfr/Cargo.toml
- ntfs2ntfs/Cargo.toml
- restrict-validity-period/Cargo.toml
Using [`cargo-machete`](https://github.com/bnjbvr/cargo-machete). Weirdly, [`cargo-udeps`](https://github.com/est31/cargo-udeps) doesn't seem to report them :thinking:
> feat: remove unused dependencies

- Cargo.toml
Driven by the error in https://github.com/hove-io/loki/pull/322.
> feat: bump to 'chrono-tz:0.7.0'

- .github/workflows/continuous-integration.yml
Better to test on release creation, because we don''t have `Cargo.lock`,
and therefore potential crate updates since the last merge master
> [tech] Github Actions runners - Simplification on release creation and push

- .github/dependabot.yml
Add some automatic dependency update to the repository. Can be done `daily`, `weekly` or `monthly`. `daily` is probably too frequent, so I'm proposing `weekly`.
> ci: configure 'dependanbot' for 'cargo' and 'github-actions'

- Cargo.toml
- src/lib.rs
- src/model.rs
This feature, that was introduced for an experimentation, didn't prove itself safe and constrained enough. Let's remove it.
Original PR was #761. For details, opening this door of mutability was opening an opportunity to make the `Model` inconsistent. The consequence of that would be disastrous, since relations in the graph might become incorrect, the information incoherent and raise subtle bugs that might be hard to debug and fix.
> feat: remove 'mutable-model' feature

- src/objects.rs
`Default` has been implemented on `OccupancyStatus` which makes it possible to implement it on `Occupancy`. Let's do it!
> feat: implement 'Default' on 'Occupancy'

- documentation/ntfs_to_netex_france_specs.md
- src/netex_france/stops.rs
- tests/fixtures/netex_france/output/arrets.xml
about https://github.com/hove-io/transit_model/issues/888
> NetexFR : change StopPlaceType for bus

- Cargo.toml
- src/model.rs
- src/objects.rs
Seen with @pbench. We will possibly let the variation duplicates pass on `OccupancyStatus`.
It should be rare.
No clearing of occupancies dates. We will see in the future if necessary.
> Add deduplication on occupancies

- Cargo.toml
Mergify is not used anymore. And since I was removing this, I noticed a few other files and folders could be excluded as well.
> chore: clean-up of the crate's included files

- .github/workflows/continuous-integration-deb11.yml
- Dockerfile_deb11
Note on GithubActions: temporary duplication of Continuous-Integration.
For more security, it's better to segment (tests + builds) for various versions of Debian (9 and 11).
> Add Debian11 image builds

- Makefile
by default `cargo test` build doc tests`
see https://doc.rust-lang.org/cargo/commands/cargo-test.html#target-selection
> [ci] cargo test also builds doc tests

- Cargo.toml
Cause `0.61` was always released (without Cargo bump)
> [fix] Bump TransitModel 0.62.0

- Cargo.toml
- src/utils.rs
updates
`chrono-tz` 0.8 → 0.9
`geo` 0.27 → 0.28
`zip` 0.6 → 2
> Cargo updates

- Cargo.toml
- src/lib.rs
- src/ntfs/mod.rs
- src/objects.rs
- tests/fixtures/gtfs2ntfs/full_output/feed_infos.txt
- tests/fixtures/gtfs2ntfs/minimal/output/feed_infos.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output/feed_infos.txt
- tests/fixtures/gtfs2ntfs/routes_comments/output_as_lines/feed_infos.txt
- tests/fixtures/ntfs/odt_reservations.txt
- tests/fixtures/restrict-validity-period/output/feed_infos.txt
- tests/read_ntfs.rs
Adaptation to ntfs v0.16.1: renaming of `odt_reservation_condition` in [odt_reservations.txtl](https://github.com/hove-io/ntfs-specification/blob/master/extensions/odt_reservation.md#odt_reservationstxt-optionnel)
Ref. NAV-3327
> [tech] Adaptation to ntfs v0.16.1

- Cargo.toml
- ntfs2gtfs/tests/fixtures/output/shapes.txt
- src/gtfs/mod.rs
- src/gtfs/read.rs
- src/gtfs/write.rs
Revert https://github.com/hove-io/transit_model/pull/980 as it does not respect GTFS specification
To merge after August 4
Ref. DHUB-1500
> [fix] [ntfs2gtfs] Only create shapes for trips
